import { useSession } from 'next-auth/react'
import Head from 'next/head'

import { api } from '@/utils/api'

export default function Block() {
  const utils = api.useUtils()
  const addBlock = api.blocks.create.useMutation({
    async onSuccess() {
      await utils.blocks.getLatest.invalidate()
    },
  })
  const blocks = api.blocks.getLatest.useQuery()

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <h1>
            Yo <span>T3</span> App
          </h1>
          <button
            disabled={addBlock.isLoading || blocks.isLoading}
            onClick={async () => {
              try {
                await addBlock.mutateAsync({ text: 'yoyoy' })
              } catch (error) {
                console.log('error')
              }
            }}
          >
            add block
          </button>
          {blocks && blocks.data?.title}
          {blocks && blocks.data?.createdbyId}
          <div>{/* <AuthShowcase /> */}</div>
        </div>
      </main>
    </>
  )
}

function AuthShowcase() {
  const { data: sessionData } = useSession()

  const { data: secretMessage } = api.post.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined },
  )

  return (
    <div>
      <p>
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      {/* <button
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? 'Sign out' : 'Sign in'}
      </button> */}
    </div>
  )
}
